### ISSUE TITLE
Add more documentation?

### ISSUE THREAD

**Issue by yaoyuhan** [finagle29/DBSP_DRP#2]
Hi Milan:

Thanks for writing this very nice pipeline! I have a few suggestions 
- In the README file, the `-o` should be changed to `-d`. It would be great if you can highlight a link to [here](https://dbsp-drp.readthedocs.io/en/latest/?badge=latest). It took me a while to discover that many of tips are not in the README file but in the documentation page.
- When I download the telluric file and put it to pypeit/data/telluric/, I guess I don't need to change the file name, right? If so, I suggest that in [this step](https://dbsp-drp.readthedocs.io/en/latest/installing.html#post-install), maybe change `$ ln /path/to/stable/pypeit/data/telluric/TellFit.fits /path/to/other/pypeit/data/telluric/TellFit.fits` to `$ ln /path/to/stable/pypeit/data/telluric/TelFit_Lick_3100_11100_R10000.fits /path/to/other/pypeit/data/telluric/TelFit_Lick_3100_11100_R10000.fits`?
- In the documentation, could you please add a new words to explain what each sub-folder in the _redux folder contains? For example, in the QA folder, I can see too html pages. I see that the Extraction.html page contains some plots. I guess the yellow line is the trace. What are the green and red lines? I see no links in the MF_A.html page, it this a TODO?

Many thanks,
Yuhan

**Comment by finagle29** [comment]
Hi Yuhan, thanks for the suggestions!
I'm sorry it took me so long to get around to all of these, but I think that I at least made a first pass at addressing all of these comments.

Could you take a look at the new docs [here](https://dbsp-drp.readthedocs.io/en/latest/qa.html) regarding the QA pages and let me know if the current state of the docs addresses your third point or if I should add more detail, maybe screenshots or an example of the `Extraction.html` page?
Thanks!

**Comment by yaoyuhan** [comment]
The updated documentation looks great. Thanks!
